Document: bloonix-plugins-apache
Title: Debian bloonix-plugins-apache Manual
Author: <insert document author here>
Abstract: This manual describes what bloonix-plugins-apache is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bloonix-plugins-apache/bloonix-plugins-apache.sgml.gz

Format: postscript
Files: /usr/share/doc/bloonix-plugins-apache/bloonix-plugins-apache.ps.gz

Format: text
Files: /usr/share/doc/bloonix-plugins-apache/bloonix-plugins-apache.text.gz

Format: HTML
Index: /usr/share/doc/bloonix-plugins-apache/html/index.html
Files: /usr/share/doc/bloonix-plugins-apache/html/*.html


